name: CI Unit tests

on:
  push:
    branches:
      - master
      - feature/**
      - release/**
      - fix/**
      - refactor/**

  pull_request:
    branches:
      - master
      - feature/**
      - release/**

jobs:
  setup-java:
    runs-on: ubuntu-latest
    outputs:
      java-version: "21"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        id: java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

  test:
    needs: setup-java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build and test all modules
        run: mvn clean test
